# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SimpleMCDA
                                 A QGIS plugin
 This plugin will allow users to implement a simple single synthesis MCDA. Put simply this plugin will create a composite variable through the use of weights, and raw variables. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-17
        copyright            : (C) 2018 by Ryerson University
        email                : renacin.matadeen@ryerson.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SimpleMCDA class from file SimpleMCDA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SimpleMCDA import SimpleMCDA
    return SimpleMCDA(iface)
